### ISSUE TITLE
Muilt-arch doesn't seem to work

### ISSUE THREAD

**Issue by vilgotf** [redhat-actions/buildah-build#60]
### Version
redhat-action/buildah-build@v2

### Describe the bug
Using archs: amd64,arm64 I expect it to build amd64 & arm64 images (like the docs state), but the command that is run is incorrect according to the buildah docs (--arch takes only one argument but it is given two)

### Steps to reproduce, workflow links, screenshots
https://github.com/vilgotf/voice-pruner/runs/3013577143

**Comment by tetchel** [comment]
I think this is the same issue as https://github.com/redhat-actions/buildah-build/issues/24#issuecomment-792000579 

Can you try pulling the image ahead of time?

**Comment by vilgotf** [comment]
Using matrix build doesn't work since that builds & pushes amd64 and then builds & pushes arm64 (overwriting amd64 instead of adding to it). Pulling the base images before issuing `buildah bud ...` resulted in the same error when running locally (F34, buildah 1.21.0)

**Comment by tetchel** [comment]
OK, I see what you mean. I know we had some users in the past doing the comma-separated archs, but maybe it wasn't working and we/they just "thought" it was.

Try passing just one arch at a time, like you say the buildah docs specify, while I ask around.

**Comment by tetchel** [comment]
So, it seems to me there are two issues here. 

1. Passing multiple comma-separated arguments to `arch`.
As far as I can tell, you can pass anything to `arch` you like. It does not actually affect what architecture the image uses. You have to use the `FROM` clause to do that.

I used the following Containerfile for testing:
```Dockerfile
ARG ARCH=amd64
FROM ${ARCH}/alpine:3.14

RUN echo "hello world"

ENTRYPOINT [ "sh", "-c", "uname -a && echo -n 'Bits: ' && getconf LONG_BIT && echo 'goodbye world'" ]
```

then:
```sh
export ARCH=arm64v8
export TAG=quay.io/tetchell/buildah-multiarch:latest
buildah bud -t $TAG --arch $ARCH --build-arg ARCH=$ARCH -f Containerfile

[ /src/tetchel/buildah-multiarch ] 26 (main) $ podman run quay.io/tetchell/buildah-multiarch:latest
Linux 98c394deb27b 5.12.11-200.fc33.x86_64 #1 SMP Wed Jun 16 16:10:53 UTC 2021 aarch64 Linux
64
goodbye world
```
https://github.com/docker-library/official-images#architectures-other-than-amd64

I definitely agree with you that the README is terribly misleading and I will remove the comma-separated example, and replace "archs" with "arch" but leave the plural input intact (but undocumented) so as not to break existing users.

2. "overwriting amd64 instead of adding to it"

If you want multiple images referred to by the same tag, you have to use buildah's `manifest` feature. This is presently not supported by this action, so you would have to write a script for those steps yourself after building the images.

https://github.com/containers/buildah/blob/main/docs/buildah-manifest.md

There is a great breakdown of multi-arch support in this issue. 
https://github.com/containers/buildah/issues/1590

**Comment by vilgotf** [comment]
Would be great if `manifest` could be added to this action! (I worked around this [here](https://github.com/vilgotf/voice-pruner/actions/runs/1014776358/workflow))

**Comment by Divyansh42** [comment]
Done in https://github.com/redhat-actions/buildah-build/pull/62
